In [2]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None)
import time
import numpy as np

In [3]:
stats_url = "https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2012-13&SeasonType=Regular%20Season&StatCategory=PTS"

In [4]:
r = requests.get(url = stats_url ).json()

In [5]:
table_headers = r['resultSet']['headers']

In [6]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [17]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
temp_df2 = pd.DataFrame({'Year': ['2012-13' for i in range(len(temp_df1))], 
                         'Season':['Regular%20Season' for i in range(len(temp_df1))]} )
temp_df3 = pd.concat([temp_df2, temp_df1], axis = 1)
temp_df3

,Year,Season,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2012-13,Regular%20Season,1628369,1,Jayson Tatum,1610612738,BOS,24,983,201,472,0.426,77,196,0.393,136,170,0.800,24,137,161,148,29,21,100,72,615,569,1.48,0.29
1,2012-13,Regular%20Season,201939,2,Stephen Curry,1610612744,GSW,22,764,202,440,0.459,91,229,0.397,107,129,0.829,11,104,115,129,29,8,57,59,602,566,2.26,0.51
2,2012-13,Regular%20Season,1627759,3,Jaylen Brown,1610612738,BOS,24,920,197,419,0.470,60,161,0.373,100,131,0.763,33,133,166,85,27,10,74,71,554,515,1.15,0.36
3,2012-13,Regular%20Season,1629029,4,Luka Dončić,1610612742,DAL,15,552,160,352,0.455,51,148,0.345,104,135,0.770,10,137,147,96,27,9,59,44,475,472,1.63,0.46
4,2012-13,Regular%20Season,202710,5,Jimmy Butler,1610612748,MIA,17,629,166,328,0.506,23,68,0.338,111,132,0.841,41,84,125,78,35,11,25,25,466,507,3.12,1.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2012-13,Regular%20Season,1629006,206,Josh Okogie,1610612750,MIN,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2012-13,Regular%20Season,1630556,206,Kessler Edwards,1610612751,BKN,2,7,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,1,0,1,3,0,1,1.00,1.00
214,2012-13,Regular%20Season,1630201,206,Malachi Flynn,1610612761,TOR,6,36,0,7,0.000,0,3,0.000,0,0,0.000,2,1,3,3,1,0,1,6,0,-1,3.00,1.00
215,2012-13,Regular%20Season,202693,206,Markieff Morris,1610612748,MIA,2,3,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,1,2,0,-1,0.00,0.00
216,2012-13,Regular%20Season,200794,206,Paul Millsap,1610612755,PHI,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,1,1,1,0,0,0,1,0,2,0.00,0.00

In [8]:
del temp_df1, temp_df2, temp_df3

In [9]:
df_cols = ['Year', 'Season_type'] + table_headers

In [10]:
pd.DataFrame(columns= df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [11]:
headers = {
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7",
    "connection": "keep-alive",
    "host": "stats.nba.com",
    "origin": "https://www.nba.com",
    "referer": "https://www.nba.com/",
    "sec-ch-ua": '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
}

In [20]:
df = pd.DataFrame(columns= df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21','2021-22']

start_loop = time.time()
for y in years:
    for s in season_types:
        url_api = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url = url_api, headers=headers).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)
        temp_df2 = pd.DataFrame({'Year': [y for i in range(len(temp_df1))], 
                                 'Season_type':[s for i in range(len(temp_df1))]} )
        temp_df3 = pd.concat([temp_df2, temp_df1], axis = 1)
        df = pd.concat([df, temp_df3], axis = 0)
        print(f'Finished scraping data for the {y} {s}.')
        lag = np.random.uniform(low=1,high=3)
        print(f'....waiting {round(lag,1)} seconds')
        time.sleep(lag)
print(f'Process completed! Total run time: {round((time.time()-start_loop)/60,2)}')
df.to_excel('nba_player_data.xlsx', index= False)

C:\Users\246ha\AppData\Local\Temp\ipykernel_10508\4268014764.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, temp_df3], axis = 0)

Finished scraping data for the 2012-13 Regular%20Season.
....waiting 2.2 seconds
Finished scraping data for the 2012-13 Playoffs.
....waiting 2.6 seconds
Finished scraping data for the 2013-14 Regular%20Season.
....waiting 1.0 seconds
Finished scraping data for the 2013-14 Playoffs.
....waiting 1.4 seconds
Finished scraping data for the 2014-15 Regular%20Season.
....waiting 1.0 seconds
Finished scraping data for the 2014-15 Playoffs.
....waiting 2.1 seconds
Finished scraping data for the 2015-16 Regular%20Season.
....waiting 2.7 seconds
Finished scraping data for the 2015-16 Playoffs.
....waiting 2.8 seconds
Finished scraping data for the 2016-17 Regular%20Season.
....waiting 1.8 seconds
Finished scraping data for the 2016-17 Playoffs.
....waiting 1.3 seconds
Finished scraping data for the 2017-18 Regular%20Season.
....waiting 1.0 seconds
Finished scraping data for the 2017-18 Playoffs.
....waiting 2.3 seconds
Finished scraping data for the 2018-19 Regular%20Season.
....waiting 1.4 seconds
Finished scraping data for the 2018-19 Playoffs.
....waiting 2.7 seconds
Finished scraping data for the 2019-20 Regular%20Season.
....waiting 1.6 seconds
Finished scraping data for the 2019-20 Playoffs.
....waiting 1.2 seconds
Finished scraping data for the 2020-21 Regular%20Season.
....waiting 2.5 seconds
Finished scraping data for the 2020-21 Playoffs.
....waiting 2.7 seconds
Finished scraping data for the 2021-22 Regular%20Season.
....waiting 2.7 seconds
Finished scraping data for the 2021-22 Playoffs.
....waiting 2.0 seconds
Process completed! Total run time: 0.77

In [21]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2012-13,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,2012-13,Regular%20Season,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2012-13,Regular%20Season,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,2012-13,Regular%20Season,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2012-13,Regular%20Season,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212,2021-22,Playoffs,1629006,206,Josh Okogie,1610612750,MIN,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
213,2021-22,Playoffs,1630556,206,Kessler Edwards,1610612751,BKN,2,7,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,1,0,1,3,0,1,1.00,1.00
214,2021-22,Playoffs,1630201,206,Malachi Flynn,1610612761,TOR,6,36,0,7,0.000,0,3,0.000,0,0,0.000,2,1,3,3,1,0,1,6,0,-1,3.00,1.00
215,2021-22,Playoffs,202693,206,Markieff Morris,1610612748,MIA,2,3,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,1,2,0,-1,0.00,0.00
216,2021-22,Playoffs,200794,206,Paul Millsap,1610612755,PHI,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,1,1,1,0,0,0,1,0,2,0.00,0.00